import json
import os

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🚀 Advanced CIFAR-10 Classification: ResNet-18, Mixup & Augmentation\n",
    "**Goal**: Intelligent accuracy improvement from ~86-87% to **>92%+** on CIFAR-10.\n",
    "\n",
    "### Key Enhancements:\n",
    "1. **Architecture**: Upgrade from Simple 3-block CNN to **ResNet-18** with Residual Skip Connections.\n",
    "2. **Data Augmentation**: Reflected padding crops, Random Horizontal Flips, Color Jitter, Rotation, and **Random Erasing (Cutout)**.\n",
    "3. **Regularization & Regularized Loss**: **Mixup** ($\alpha=0.2$) + **Label Smoothing** ($0.1$).\n",
    "4. **Optimization**: **AdamW** with **OneCycleLR / CosineAnnealingLR** scheduling."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 1: Imports & Reproducibility ──────────────────────────────────────\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torchvision\n",
    "import torchvision.transforms as transforms\n",
    "from torch.utils.data import DataLoader\n",
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "import random, os\n",
    "\n",
    "SEED = 42\n",
    "random.seed(SEED)\n",
    "np.random.seed(SEED)\n",
    "torch.manual_seed(SEED)\n",
    "torch.backends.cudnn.deterministic = True\n",
    "\n",
    "DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f'Using device: {DEVICE}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 2: Hyperparameters ─────────────────────────────────────────────────\n",
    "BATCH_SIZE      = 128\n",
    "EPOCHS          = 30\n",
    "LR              = 1e-3\n",
    "WEIGHT_DECAY    = 1e-4\n",
    "MIXUP_ALPHA     = 0.2\n",
    "LABEL_SMOOTH    = 0.1\n",
    "NUM_WORKERS     = 2\n",
    "\n",
    "CIFAR10_MEAN = (0.4914, 0.4822, 0.4465)\n",
    "CIFAR10_STD  = (0.2023, 0.1994, 0.2010)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 3: Advanced Transforms Pipeline ────────────────────────────────────\n",
    "transform_base = transforms.Compose([\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(CIFAR10_MEAN, CIFAR10_STD),\n",
    "])\n",
    "\n",
    "transform_improved = transforms.Compose([\n",
    "    transforms.RandomCrop(32, padding=4, padding_mode='reflect'),\n",
    "    transforms.RandomHorizontalFlip(p=0.5),\n",
    "    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),\n",
    "    transforms.RandomRotation(degrees=15),\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(CIFAR10_MEAN, CIFAR10_STD),\n",
    "    transforms.RandomErasing(p=0.25, scale=(0.02, 0.2), value='random'),\n",
    "])\n",
    "\n",
    "transform_test = transforms.Compose([\n",
    "    transforms.ToTensor(),\n",
    "    transforms.Normalize(CIFAR10_MEAN, CIFAR10_STD),\n",
    "])\n",
    "\n",
    "print('Data Augmentations & Transforms Defined.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 4: Datasets & Loaders ──────────────────────────────────────────────\n",
    "train_base = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform_base)\n",
    "train_imp  = torchvision.datasets.CIFAR10(root='./data', train=True, download=False, transform=transform_improved)\n",
    "test_set   = torchvision.datasets.CIFAR10(root='./data', train=False, download=False, transform=transform_test)\n",
    "\n",
    "loader_base_train = DataLoader(train_base, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)\n",
    "loader_imp_train  = DataLoader(train_imp,  batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS, pin_memory=True)\n",
    "loader_test       = DataLoader(test_set,   batch_size=256,        shuffle=False, num_workers=NUM_WORKERS, pin_memory=True)\n",
    "\n",
    "CLASSES = test_set.classes\n",
    "print(f'Train samples: {len(train_base):,} | Test samples: {len(test_set):,}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 5: Mixup Implementation ────────────────────────────────────────────\n",
    "def mixup_data(x, y, alpha=0.2):\n",
    "    if alpha > 0:\n",
    "        lam = np.random.beta(alpha, alpha)\n",
    "    else:\n",
    "        lam = 1.0\n",
    "    batch_size = x.size(0)\n",
    "    index = torch.randperm(batch_size).to(x.device)\n",
    "    mixed_x = lam * x + (1 - lam) * x[index]\n",
    "    y_a, y_b = y, y[index]\n",
    "    return mixed_x, y_a, y_b, lam\n",
    "\n",
    "def mixup_criterion(criterion, pred, y_a, y_b, lam):\n",
    "    return lam * criterion(pred, y_a) + (1 - lam) * criterion(pred, y_b)\n",
    "\n",
    "print('Mixup functions configured.')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 6: Modern ResNet-18 Architecture for CIFAR-10 ───────────────────────\n",
    "class BasicBlock(nn.Module):\n",
    "    expansion = 1\n",
    "    def __init__(self, in_planes, planes, stride=1):\n",
    "        super(BasicBlock, self).__init__()\n",
    "        self.conv1 = nn.Conv2d(in_planes, planes, kernel_size=3, stride=stride, padding=1, bias=False)\n",
    "        self.bn1 = nn.BatchNorm2d(planes)\n",
    "        self.relu = nn.ReLU(inplace=True)\n",
    "        self.conv2 = nn.Conv2d(planes, planes, kernel_size=3, stride=1, padding=1, bias=False)\n",
    "        self.bn2 = nn.BatchNorm2d(planes)\n",
    "\n",
    "        self.shortcut = nn.Sequential()\n",
    "        if stride != 1 or in_planes != self.expansion * planes:\n",
    "            self.shortcut = nn.Sequential(\n",
    "                nn.Conv2d(in_planes, self.expansion * planes, kernel_size=1, stride=stride, bias=False),\n",
    "                nn.BatchNorm2d(self.expansion * planes)\n",
    "            )\n",
    "\n",
    "    def forward(self, x):\n",
    "        out = self.relu(self.bn1(self.conv1(x)))\n",
    "        out = self.bn2(self.conv2(out))\n",
    "        out += self.shortcut(x)\n",
    "        out = self.relu(out)\n",
    "        return out\n",
    "\n",
    "class ResNet18CIFAR(nn.Module):\n",
    "    def __init__(self, num_classes=10):\n",
    "        super(ResNet18CIFAR, self).__init__()\n",
    "        self.in_planes = 64\n",
    "        self.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)\n",
    "        self.bn1 = nn.BatchNorm2d(64)\n",
    "        self.relu = nn.ReLU(inplace=True)\n",
    "        self.layer1 = self._make_layer(BasicBlock, 64, 2, stride=1)\n",
    "        self.layer2 = self._make_layer(BasicBlock, 128, 2, stride=2)\n",
    "        self.layer3 = self._make_layer(BasicBlock, 256, 2, stride=2)\n",
    "        self.layer4 = self._make_layer(BasicBlock, 512, 2, stride=2)\n",
    "        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))\n",
    "        self.dropout = nn.Dropout(0.3)\n",
    "        self.fc = nn.Linear(512 * BasicBlock.expansion, num_classes)\n",
    "\n",
    "    def _make_layer(self, block, planes, num_blocks, stride):\n",
    "        strides = [stride] + [1]*(num_blocks-1)\n",
    "        layers = []\n",
    "        for stride in strides:\n",
    "            layers.append(block(self.in_planes, planes, stride))\n",
    "            self.in_planes = planes * block.expansion\n",
    "        return nn.Sequential(*layers)\n",
    "\n",
    "    def forward(self, x):\n",
    "        out = self.relu(self.bn1(self.conv1(x)))\n",
    "        out = self.layer1(out)\n",
    "        out = self.layer2(out)\n",
    "        out = self.layer3(out)\n",
    "        out = self.layer4(out)\n",
    "        out = self.avgpool(out)\n",
    "        out = torch.flatten(out, 1)\n",
    "        out = self.dropout(out)\n",
    "        out = self.fc(out)\n",
    "        return out\n",
    "\n",
    "model_test = ResNet18CIFAR()\n",
    "num_params = sum(p.numel() for p in model_test.parameters() if p.requires_grad)\n",
    "print(f'ResNet-18 Total Parameters: {num_params:,}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 7: Training & Evaluation Functions ─────────────────────────────────\n",
    "def train_one_epoch(model, loader, criterion, optimizer, scheduler, use_mixup=False):\n",
    "    model.train()\n",
    "    total_loss, correct, total = 0., 0, 0\n",
    "    for imgs, labels in loader:\n",
    "        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)\n",
    "        optimizer.zero_grad()\n",
    "        \n",
    "        if use_mixup:\n",
    "            imgs_m, y_a, y_b, lam = mixup_data(imgs, labels, alpha=MIXUP_ALPHA)\n",
    "            outputs = model(imgs_m)\n",
    "            loss = mixup_criterion(criterion, outputs, y_a, y_b, lam)\n",
    "            correct += (lam * (outputs.argmax(1) == y_a).sum().item() + (1 - lam) * (outputs.argmax(1) == y_b).sum().item())\n",
    "        else:\n",
    "            outputs = model(imgs)\n",
    "            loss = criterion(outputs, labels)\n",
    "            correct += (outputs.argmax(1) == labels).sum().item()\n",
    "            \n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        total_loss += loss.item() * imgs.size(0)\n",
    "        total += imgs.size(0)\n",
    "        \n",
    "    scheduler.step()\n",
    "    return total_loss / total, correct / total\n",
    "\n",
    "@torch.no_grad()\n",
    "def evaluate(model, loader, criterion):\n",
    "    model.eval()\n",
    "    total_loss, correct, total = 0., 0, 0\n",
    "    for imgs, labels in loader:\n",
    "        imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)\n",
    "        outputs = model(imgs)\n",
    "        loss = criterion(outputs, labels)\n",
    "        total_loss += loss.item() * imgs.size(0)\n",
    "        correct += (outputs.argmax(1) == labels).sum().item()\n",
    "        total += imgs.size(0)\n",
    "    return total_loss / total, correct / total\n",
    "\n",
    "def train_model(name, model, train_loader, use_mixup=False):\n",
    "    print(f'\\n' + '='*55)\n",
    "    print(f'  Training: {name}')\n",
    "    print('='*55)\n",
    "    \n",
    "    criterion = nn.CrossEntropyLoss(label_smoothing=LABEL_SMOOTH if use_mixup else 0.0)\n",
    "    optimizer = optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)\n",
    "    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)\n",
    "    \n",
    "    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}\n",
    "    \n",
    "    for epoch in range(1, EPOCHS + 1):\n",
    "        tr_loss, tr_acc = train_one_epoch(model, train_loader, criterion, optimizer, scheduler, use_mixup=use_mixup)\n",
    "        va_loss, va_acc = evaluate(model, loader_test, criterion)\n",
    "        history['train_loss'].append(tr_loss)\n",
    "        history['train_acc'].append(tr_acc)\n",
    "        history['val_loss'].append(va_loss)\n",
    "        history['val_acc'].append(va_acc)\n",
    "        \n",
    "        if epoch % 5 == 0 or epoch == 1 or epoch == EPOCHS:\n",
    "            print(f'  Epoch {epoch:02d}/{EPOCHS}  '\n",
    "                  f'train_loss={tr_loss:.4f}  train_acc={tr_acc*100:.1f}%  '\n",
    "                  f'val_loss={va_loss:.4f}  val_acc={va_acc*100:.1f}%')\n",
    "                  \n",
    "    print(f'\\n  ✔ Final Test Accuracy ({name}): {history[\"val_acc\"][-1]*100:.2f}% | Best: {max(history[\"val_acc\"])*100:.2f}%')\n",
    "    return model, history"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 8: Execute Training Runs ───────────────────────────────────────────\n",
    "# Model 1: Baseline Simple CNN (Normal pipeline)\n",
    "# Model 2: Improved ResNet-18 (Advanced Aug + Mixup + Label Smoothing)\n",
    "from data_augmentation_comparison import SimpleCNN\n",
    "\n",
    "model_baseline = SimpleCNN().to(DEVICE)\n",
    "model_baseline, hist_baseline = train_model('Baseline SimpleCNN', model_baseline, loader_base_train, use_mixup=False)\n",
    "\n",
    "model_resnet = ResNet18CIFAR().to(DEVICE)\n",
    "model_resnet, hist_resnet = train_model('Improved ResNet-18 + Mixup', model_resnet, loader_imp_train, use_mixup=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 9: Plot Performance Comparison ────────────────────────────────────\n",
    "epochs_range = range(1, EPOCHS + 1)\n",
    "fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
    "\n",
    "# Loss Plot\n",
    "axes[0].plot(epochs_range, hist_baseline['train_loss'], 'b--', label='Baseline Train Loss')\n",
    "axes[0].plot(epochs_range, hist_baseline['val_loss'], 'b-', label='Baseline Val Loss')\n",
    "axes[0].plot(epochs_range, hist_resnet['train_loss'], 'g--', label='ResNet-18 Train Loss')\n",
    "axes[0].plot(epochs_range, hist_resnet['val_loss'], 'g-', label='ResNet-18 Val Loss')\n",
    "axes[0].set_title('Training & Validation Loss Comparison', fontsize=12)\n",
    "axes[0].set_xlabel('Epochs')\n",
    "axes[0].set_ylabel('Loss')\n",
    "axes[0].legend()\n",
    "axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "# Accuracy Plot\n",
    "axes[1].plot(epochs_range, [acc*100 for acc in hist_baseline['train_acc']], 'b--', label='Baseline Train Acc')\n",
    "axes[1].plot(epochs_range, [acc*100 for acc in hist_baseline['val_acc']], 'b-', label='Baseline Val Acc')\n",
    "axes[1].plot(epochs_range, [acc*100 for acc in hist_resnet['train_acc']], 'g--', label='ResNet-18 Train Acc')\n",
    "axes[1].plot(epochs_range, [acc*100 for acc in hist_resnet['val_acc']], 'g-', label='ResNet-18 Val Acc')\n",
    "axes[1].set_title('Training & Validation Accuracy Comparison (%)', fontsize=12)\n",
    "axes[1].set_xlabel('Epochs')\n",
    "axes[1].set_ylabel('Accuracy (%)')\n",
    "axes[1].legend()\n",
    "axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('improved_resnet18_comparison.png', dpi=120, bbox_inches='tight')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Cell 10: Summary & Analysis ──────────────────────────────────────────────\n",
    "final_base = hist_baseline['val_acc'][-1] * 100\n",
    "final_res  = hist_resnet['val_acc'][-1] * 100\n",
    "best_base  = max(hist_baseline['val_acc']) * 100\n",
    "best_res   = max(hist_resnet['val_acc']) * 100\n",
    "\n",
    "gap_base = (hist_baseline['train_acc'][-1] - hist_baseline['val_acc'][-1]) * 100\n",
    "gap_res  = (hist_resnet['train_acc'][-1] - hist_resnet['val_acc'][-1]) * 100\n",
    "\n",
    "print('\\n' + '='*55)\n",
    "print('      ACCURACY IMPROVEMENT SUMMARY — CIFAR-10')\n",
    "print('='*55)\n",
    "print(f'  {\"Metric\":<30} {\"Baseline SimpleCNN\":>18}  {\"Improved ResNet-18\":>18}')\n",
    "print('-'*55)\n",
    "print(f'  {\"Final Test Accuracy\":<30} {final_base:>17.2f}%  {final_res:>17.2f}%')\n",
    "print(f'  {\"Best Test Accuracy\":<30} {best_base:>17.2f}%  {best_res:>17.2f}%')\n",
    "print(f'  {\"Overfitting Gap (Train - Val)\":<30} {gap_base:>17.2f}%  {gap_res:>17.2f}%')\n",
    "print('='*55)\n",
    "print(f'  Accuracy Improvement:  +{final_res - final_base:.2f}%')\n",
    "print(f'  Generalization Gap:    {gap_base:.2f}% -> {gap_res:.2f}%')\n",
    "print('='*55)"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open('/home/adithya/Development/adithyasean/computer-vision/notebooks/data_augmentation_improved.ipynb', 'w') as f:
    json.dump(notebook, f, indent=1)

print('Successfully generated data_augmentation_improved.ipynb')
